spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: app
            client-secret: app
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8083/login/oauth2/code/my-client
        provider:
          my-client:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token
            user-info-uri: http://localhost:8080/userInfo
            userNameAttribute: username


server:
  port: 8083
