spring:
  application:
    name: discovery-client
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/