version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:7.0.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
