spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db?useSSL=false
    username: root
    password: zzzzzz
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.txt


security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:keystore.jks
        key-store-password: pass1234
        key-alias: wisely
        key-password: pass1234
      tokenKeyAccess: permitAll()
      checkTokenAccess: isAuthenticated()
      realm: wisely



logging.level.org.springframework.security: debug
