version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: wisely
      RABBITMQ_DEFAULT_PASS: zzzzzz