spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db?useSSL=false
    username: root
    password: zzzzzz
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#  flyway:
#    baseline-version: 1
#    schemas: first_db


