spring:
  application:
    name: auth-server

management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/