#spring:
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          endpoints: localhost:9200
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: wisely
      password: zzzzzz
      database: first_db