version: '3.1'

services:
  artemis:
    image: vromero/activemq-artemis
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ARTEMIS_USERNAME: wisely
      ARTEMIS_PASSWORD: zzzzzz